spring:
  datasource:
    url: jdbc:mysql://10.21.23.42:3306/golden_age?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: 1127-account
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.23.163
        namespace: 1127

weIdentity:
  cpt_template_path: cpt_template/cpt001.json
server:
  port: 9010
