server:
  port: 8000
spring:
  application:
    name: 1127-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.23.163
        namespace: 1127
    gateway:
      discovery:
        locator:
          enabled: true

white-path:
    - /1127-account/account/login
    - /1127-account/account/userRegisterApplicant
